version: '2.2'

services:
  nginx:
    image: nginx
    init: true
    depends_on:
     - mariadb
    build:
      context: ./requirements/nginx
    networks:
     - my_net
    ports:
     - "443:443"
    volumes:
     - wordpress_vol:/var/www/dszklarz.42.fr
    restart: unless-stopped

  mariadb:
    image: mariadb
    init: true
    build:
      context: ./requirements/mariadb
    env_file:
     - ./.env
    networks:
     - my_net
    volumes:
     - mariadb_vol:/var/lib/mysql
    expose:
     - "3306"
    ports:
     - "3306:3306"
    restart: unless-stopped

  wordpress:
    image: wp-test
    init: true
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
     - ./.env
    networks:
     - my_net
    volumes:
     - wordpress_vol:/var/www/wordpress
    expose:
     - "9001"
    restart: unless-stopped

volumes:
  mariadb_vol:
    name: "mariadb_vol"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /home/dszklarz/volumes/mariadb
  wordpress_vol:
    name: "wordpress_vol"
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /home/dszklarz/volumes/wordpress
networks:
  my_net:
    name: "my_net"